openapi: 3.0.0
info:
  title: 'Hello, REST'
  description: A simple app to get the name of the user.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local dev server
paths:
  '/hello/{name}':
    get:
      summary: Retrieves the name of the user and says hello.
      parameters:
        - name: name
          in: path
          required: true
          description: name of the user
          schema:
            type: string
      responses:
        '200':
          description: 'Hello, ${name}'
        '422':
          description: Must be a valid name to return.
