openapi: 3.0.0
info:
  title: Quote of the Day
  description: A simple API for Author and Quotes
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: Local dev server
  
paths:
  /quote:
    get:
      summary: Returns the Author and the Quote in a JSON format randomly
      responses:
        '200':
          description: AUthor and Quote object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
              
components:
  schemas:
  
    Quote:
      type: object
      properties:
        Author:
          type: string
        Quote:
          type: string
          