openapi: 3.0.0
info:
  title: Word of the Day
  description: A simple API for Returning Word definitions
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: Local dev server
  
paths:
  /quote:
    get:
      summary: Returns the Word and the Definition in a JSON format randomly
      responses:
        '200':
          description: Word and Definition Object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Word'
              
components:
  schemas:
  
    Word:
      type: object
      properties:
        Word:
          type: string
        Definition:
          type: string
          